In [1]:
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /gdrive
/gdrive


In [3]:
cd My\ Drive

/gdrive/My Drive


In [4]:
cd Colab\ Notebooks

/gdrive/My Drive/Colab Notebooks


In [5]:
cd Accident-Images-Analysis-Dataset-master/

/gdrive/My Drive/Colab Notebooks/Accident-Images-Analysis-Dataset-master


In [6]:
cd Accident\ Images\ Analysis\ Dataset

/gdrive/My Drive/Colab Notebooks/Accident-Images-Analysis-Dataset-master/Accident Images Analysis Dataset


In [7]:
cd Accident\ -Detection

/gdrive/My Drive/Colab Notebooks/Accident-Images-Analysis-Dataset-master/Accident Images Analysis Dataset/Accident -Detection


In [8]:
ls

1/  AccidentDetection.ipynb  LoadingModel.ipynb
2/  Accident_Recognition.h5  readme.txt


In [10]:
from keras.models import load_model
model = load_model("Accident_Recognition.h5")
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_5 (Conv2D)            (None, 28, 28, 16)        1216      
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 14, 14, 16)        0         
_________________________________________________________________
dropout_11 (Dropout)         (None, 14, 14, 16)        0         
_________________________________________________________________
conv2d_6 (Conv2D)            (None, 10, 10, 32)        12832     
_________________________________________________________________
max_pooling2d_6 (MaxPooling2 (None, 5, 5, 32)          0         
_________________________________________________________________
dropout_12 (Dropout)         (None, 5, 5, 32)          0         
_________________________________________________________________
flatten_3 (Flatten)          (None, 800)               0         
__________

In [0]:
from keras.preprocessing import image
X_train = []
img = image.load_img('1/'+'1.jpg',target_size = (32,32,3))

In [0]:
img = image.img_to_array(img)
img = img/255
X_train.append(img)

In [0]:
import numpy as np
X_train = np.asarray(X_train)
pred = model.predict(X_train)

In [19]:
print(pred)

[[1.1148634e-06]]


In [24]:

np.round(pred) == 0

array([[ True]])

In [0]:
Acc_img = []
img = image.load_img('Accident1.jpg',target_size = (32,32,3))
img = image.img_to_array(img)
img = img/255
Acc_img.append(img)

In [0]:
Acc_img = np.asarray(Acc_img)

In [32]:
Acc_img.shape

(1, 32, 32, 3)

In [33]:
pred = model.predict(Acc_img)
np.round(pred) == 1

array([[ True]])

In [35]:
pred

array([[1.]], dtype=float32)

In [36]:
A = np.arange(20)
B = np.zeros(5)
np.append(A,B)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.,  0.,  0.,  0.,  0.,  0.])

In [0]:
A = np.append(A,B)

In [45]:
X_train = []
img = image.load_img("FamilyPic.png",target_size = (32,32,3))
img = image.img_to_array(img)
img = img/255
X_train.append(img)

X_train = np.asarray(X_train)
pred = model.predict(X_train)
0 == np.round(pred)

array([[False]])

In [44]:
pred

array([[1.]], dtype=float32)